curl -i -X GET 'https://graph.facebook.com/v17.0/<WHATSAPP_BUSINESS_ACCOUNT_ID>' \
  -H 'Authorization: Bearer <ACCESS_TOKEN>'
  	An access token has been generated for Mr Egyptian as following:
System user:	Me
Assigned app:	Auto Respond Bot
Access token:	EAAXTzpuJXLkBABle4CCuoHQyBww3UIFJFxv8ZCXFtjSvd89TDU8FY9Ju9Ma4uZCJfWW3ZCQmoCJn2ohGZA5FVLhlJ3MZCK8ziqzAjC5xxBxt8X2WEcGZCsZCJCg9mZBZByFWbZCZC1cwcYmIVeiFXPwoq02utZClQZC17TihTGcHLPJoO1uw6PAA7iJbb
	
Copy and save this token as it won't be stored at Facebook.
